# Morse code timing constants (in seconds)
UNIT_LENGTH = 1
DOT_MULTIPLIER = 1
DASH_MULTIPLIER = 3
INTRA_LETTER_MULTIPLIER = 1
INTER_LETTER_MULTIPLIER = 3
INTER_WORD_MULTIPLIER = 7

class Timings():
  DOT_LENGTH = UNIT_LENGTH * DOT_MULTIPLIER
  DASH_LENGTH = UNIT_LENGTH * DASH_MULTIPLIER
  INTRA_LETTER_GAP = UNIT_LENGTH * INTRA_LETTER_MULTIPLIER
  INTER_LETTER_GAP = UNIT_LENGTH * INTER_LETTER_MULTIPLIER
  INTER_WORD_GAP = UNIT_LENGTH * INTER_WORD_MULTIPLIER 
